# Generated by Django 4.1.13 on 2025-04-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_usersubmission_userprogress_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='average_time_per_question',
            field=models.FloatField(default=0.0),
        ),
    ]
