# Generated by Django 4.1.13 on 2025-04-16 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_remove_mcqquestion_options_mcqquestion_option_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=10)),
                ('expertise_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.expertiselevel')),
                ('programming_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.programminglanguage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('coding', 'Coding Question'), ('theory', 'Theory Question'), ('mcq', 'Multiple Choice Question')], max_length=10)),
                ('question_id', models.IntegerField()),
                ('user_response', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.quiz')),
            ],
        ),
    ]
