# Generated by Django 4.1.13 on 2025-04-16 19:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_quiz_quizquestionresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_type', models.CharField(choices=[('coding', 'Coding Question'), ('theory', 'Theory Question'), ('mcq', 'Multiple Choice Question')], max_length=10)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='questionembedding',
            index=models.Index(fields=['question_type'], name='interface_q_questio_51b7c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionembedding',
            unique_together={('question_id', 'question_type')},
        ),
    ]
