# Generated by Django 4.1.13 on 2025-05-03 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_questionembedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('total_coding_questions', models.IntegerField(default=8)),
                ('total_theory_questions', models.IntegerField(default=2)),
                ('coding_questions', models.ManyToManyField(related_name='assignments', to='interface.quizquestion')),
                ('expertise_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.expertiselevel')),
                ('programming_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.programminglanguage')),
                ('theory_questions', models.ManyToManyField(related_name='assignments', to='interface.theoryquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('coding', 'Coding Question'), ('theory', 'Theory Question')], max_length=10)),
                ('question_id', models.IntegerField()),
                ('user_response', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.assignment')),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('assignment', 'question_type', 'question_id')},
            },
        ),
    ]
